# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Welcome to Rotten-ScriptsðŸ¥³ Thanks for opening your first issue here! Be sure âœ”ï¸ to follow the issue template!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks ðŸ™Œ for opening this pull request! We will get back to you as soon as possible. Your patience is greatly appreciated ðŸ’–.
  PS: Please double check that you linked the corresponding issue.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull requestðŸ¥³ Feel free to take another Issue ðŸ˜ƒ

# It is recommend to include as many gifs and emojis as possible
